// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: rpcMsg.proto

package rpcMsg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControlMsgServiceClient is the client API for ControlMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlMsgServiceClient interface {
	HandleHelloMsg(ctx context.Context, in *RequestHello, opts ...grpc.CallOption) (*ResponseWelcome, error)
}

type controlMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlMsgServiceClient(cc grpc.ClientConnInterface) ControlMsgServiceClient {
	return &controlMsgServiceClient{cc}
}

func (c *controlMsgServiceClient) HandleHelloMsg(ctx context.Context, in *RequestHello, opts ...grpc.CallOption) (*ResponseWelcome, error) {
	out := new(ResponseWelcome)
	err := c.cc.Invoke(ctx, "/rpcMsg.ControlMsgService/HandleHelloMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlMsgServiceServer is the server API for ControlMsgService service.
// All implementations must embed UnimplementedControlMsgServiceServer
// for forward compatibility
type ControlMsgServiceServer interface {
	HandleHelloMsg(context.Context, *RequestHello) (*ResponseWelcome, error)
	mustEmbedUnimplementedControlMsgServiceServer()
}

// UnimplementedControlMsgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControlMsgServiceServer struct {
}

func (UnimplementedControlMsgServiceServer) HandleHelloMsg(context.Context, *RequestHello) (*ResponseWelcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleHelloMsg not implemented")
}
func (UnimplementedControlMsgServiceServer) mustEmbedUnimplementedControlMsgServiceServer() {}

// UnsafeControlMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlMsgServiceServer will
// result in compilation errors.
type UnsafeControlMsgServiceServer interface {
	mustEmbedUnimplementedControlMsgServiceServer()
}

func RegisterControlMsgServiceServer(s grpc.ServiceRegistrar, srv ControlMsgServiceServer) {
	s.RegisterService(&ControlMsgService_ServiceDesc, srv)
}

func _ControlMsgService_HandleHelloMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestHello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlMsgServiceServer).HandleHelloMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcMsg.ControlMsgService/HandleHelloMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlMsgServiceServer).HandleHelloMsg(ctx, req.(*RequestHello))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlMsgService_ServiceDesc is the grpc.ServiceDesc for ControlMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcMsg.ControlMsgService",
	HandlerType: (*ControlMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHelloMsg",
			Handler:    _ControlMsgService_HandleHelloMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcMsg.proto",
}
