// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcMsg.proto

package rpcMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPCType int32

const (
	// Request
	RPCType_REQUEST_HELLO      RPCType = 0
	RPCType_REQUEST_SETSTATION RPCType = 1
	RPCType_REQUEST_SENDFILE   RPCType = 2
	RPCType_REQUEST_SHUTDOWN   RPCType = 3
	// Response
	RPCType_RESPONSE_WELCOME  RPCType = 4
	RPCType_RESPONSE_ANNOUNCE RPCType = 5
	RPCType_RESPOSNE_INVALID  RPCType = 6
	RPCType_RESPONSE_SENFILE  RPCType = 7
	RPCType_RESPONSE_SHUTDOWN RPCType = 8
)

var RPCType_name = map[int32]string{
	0: "REQUEST_HELLO",
	1: "REQUEST_SETSTATION",
	2: "REQUEST_SENDFILE",
	3: "REQUEST_SHUTDOWN",
	4: "RESPONSE_WELCOME",
	5: "RESPONSE_ANNOUNCE",
	6: "RESPOSNE_INVALID",
	7: "RESPONSE_SENFILE",
	8: "RESPONSE_SHUTDOWN",
}

var RPCType_value = map[string]int32{
	"REQUEST_HELLO":      0,
	"REQUEST_SETSTATION": 1,
	"REQUEST_SENDFILE":   2,
	"REQUEST_SHUTDOWN":   3,
	"RESPONSE_WELCOME":   4,
	"RESPONSE_ANNOUNCE":  5,
	"RESPOSNE_INVALID":   6,
	"RESPONSE_SENFILE":   7,
	"RESPONSE_SHUTDOWN":  8,
}

func (x RPCType) String() string {
	return proto.EnumName(RPCType_name, int32(x))
}

func (RPCType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{0}
}

type RequestHello struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	UdpPort              string   `protobuf:"bytes,2,opt,name=udpPort,proto3" json:"udpPort,omitempty"`
	ControlName          string   `protobuf:"bytes,3,opt,name=controlName,proto3" json:"controlName,omitempty"`
	SrpcServerPort       string   `protobuf:"bytes,4,opt,name=srpcServerPort,proto3" json:"srpcServerPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHello) Reset()         { *m = RequestHello{} }
func (m *RequestHello) String() string { return proto.CompactTextString(m) }
func (*RequestHello) ProtoMessage()    {}
func (*RequestHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{0}
}

func (m *RequestHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHello.Unmarshal(m, b)
}
func (m *RequestHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHello.Marshal(b, m, deterministic)
}
func (m *RequestHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHello.Merge(m, src)
}
func (m *RequestHello) XXX_Size() int {
	return xxx_messageInfo_RequestHello.Size(m)
}
func (m *RequestHello) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHello.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHello proto.InternalMessageInfo

func (m *RequestHello) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *RequestHello) GetUdpPort() string {
	if m != nil {
		return m.UdpPort
	}
	return ""
}

func (m *RequestHello) GetControlName() string {
	if m != nil {
		return m.ControlName
	}
	return ""
}

func (m *RequestHello) GetSrpcServerPort() string {
	if m != nil {
		return m.SrpcServerPort
	}
	return ""
}

type ResponseWelcome struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	SongNum              uint32   `protobuf:"varint,2,opt,name=songNum,proto3" json:"songNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseWelcome) Reset()         { *m = ResponseWelcome{} }
func (m *ResponseWelcome) String() string { return proto.CompactTextString(m) }
func (*ResponseWelcome) ProtoMessage()    {}
func (*ResponseWelcome) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{1}
}

func (m *ResponseWelcome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseWelcome.Unmarshal(m, b)
}
func (m *ResponseWelcome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseWelcome.Marshal(b, m, deterministic)
}
func (m *ResponseWelcome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWelcome.Merge(m, src)
}
func (m *ResponseWelcome) XXX_Size() int {
	return xxx_messageInfo_ResponseWelcome.Size(m)
}
func (m *ResponseWelcome) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWelcome.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWelcome proto.InternalMessageInfo

func (m *ResponseWelcome) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *ResponseWelcome) GetSongNum() uint32 {
	if m != nil {
		return m.SongNum
	}
	return 0
}

type RequestSetStation struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	StationNum           uint32   `protobuf:"varint,2,opt,name=stationNum,proto3" json:"stationNum,omitempty"`
	ControlName          string   `protobuf:"bytes,3,opt,name=controlName,proto3" json:"controlName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSetStation) Reset()         { *m = RequestSetStation{} }
func (m *RequestSetStation) String() string { return proto.CompactTextString(m) }
func (*RequestSetStation) ProtoMessage()    {}
func (*RequestSetStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{2}
}

func (m *RequestSetStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSetStation.Unmarshal(m, b)
}
func (m *RequestSetStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSetStation.Marshal(b, m, deterministic)
}
func (m *RequestSetStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSetStation.Merge(m, src)
}
func (m *RequestSetStation) XXX_Size() int {
	return xxx_messageInfo_RequestSetStation.Size(m)
}
func (m *RequestSetStation) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSetStation.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSetStation proto.InternalMessageInfo

func (m *RequestSetStation) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *RequestSetStation) GetStationNum() uint32 {
	if m != nil {
		return m.StationNum
	}
	return 0
}

func (m *RequestSetStation) GetControlName() string {
	if m != nil {
		return m.ControlName
	}
	return ""
}

type ResponseAnnounce struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	SongName             string   `protobuf:"bytes,2,opt,name=songName,proto3" json:"songName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseAnnounce) Reset()         { *m = ResponseAnnounce{} }
func (m *ResponseAnnounce) String() string { return proto.CompactTextString(m) }
func (*ResponseAnnounce) ProtoMessage()    {}
func (*ResponseAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{3}
}

func (m *ResponseAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAnnounce.Unmarshal(m, b)
}
func (m *ResponseAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAnnounce.Marshal(b, m, deterministic)
}
func (m *ResponseAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAnnounce.Merge(m, src)
}
func (m *ResponseAnnounce) XXX_Size() int {
	return xxx_messageInfo_ResponseAnnounce.Size(m)
}
func (m *ResponseAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAnnounce proto.InternalMessageInfo

func (m *ResponseAnnounce) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *ResponseAnnounce) GetSongName() string {
	if m != nil {
		return m.SongName
	}
	return ""
}

type RequestSendFile struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	SongName             string   `protobuf:"bytes,2,opt,name=songName,proto3" json:"songName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSendFile) Reset()         { *m = RequestSendFile{} }
func (m *RequestSendFile) String() string { return proto.CompactTextString(m) }
func (*RequestSendFile) ProtoMessage()    {}
func (*RequestSendFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{4}
}

func (m *RequestSendFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSendFile.Unmarshal(m, b)
}
func (m *RequestSendFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSendFile.Marshal(b, m, deterministic)
}
func (m *RequestSendFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSendFile.Merge(m, src)
}
func (m *RequestSendFile) XXX_Size() int {
	return xxx_messageInfo_RequestSendFile.Size(m)
}
func (m *RequestSendFile) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSendFile.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSendFile proto.InternalMessageInfo

func (m *RequestSendFile) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *RequestSendFile) GetSongName() string {
	if m != nil {
		return m.SongName
	}
	return ""
}

type ResponseSendFile struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSendFile) Reset()         { *m = ResponseSendFile{} }
func (m *ResponseSendFile) String() string { return proto.CompactTextString(m) }
func (*ResponseSendFile) ProtoMessage()    {}
func (*ResponseSendFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{5}
}

func (m *ResponseSendFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSendFile.Unmarshal(m, b)
}
func (m *ResponseSendFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSendFile.Marshal(b, m, deterministic)
}
func (m *ResponseSendFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSendFile.Merge(m, src)
}
func (m *ResponseSendFile) XXX_Size() int {
	return xxx_messageInfo_ResponseSendFile.Size(m)
}
func (m *ResponseSendFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSendFile.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSendFile proto.InternalMessageInfo

type RequestShutdown struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	StationNum           uint32   `protobuf:"varint,2,opt,name=stationNum,proto3" json:"stationNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestShutdown) Reset()         { *m = RequestShutdown{} }
func (m *RequestShutdown) String() string { return proto.CompactTextString(m) }
func (*RequestShutdown) ProtoMessage()    {}
func (*RequestShutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{6}
}

func (m *RequestShutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestShutdown.Unmarshal(m, b)
}
func (m *RequestShutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestShutdown.Marshal(b, m, deterministic)
}
func (m *RequestShutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestShutdown.Merge(m, src)
}
func (m *RequestShutdown) XXX_Size() int {
	return xxx_messageInfo_RequestShutdown.Size(m)
}
func (m *RequestShutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestShutdown.DiscardUnknown(m)
}

var xxx_messageInfo_RequestShutdown proto.InternalMessageInfo

func (m *RequestShutdown) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *RequestShutdown) GetStationNum() uint32 {
	if m != nil {
		return m.StationNum
	}
	return 0
}

type ResponseShutdown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseShutdown) Reset()         { *m = ResponseShutdown{} }
func (m *ResponseShutdown) String() string { return proto.CompactTextString(m) }
func (*ResponseShutdown) ProtoMessage()    {}
func (*ResponseShutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b9afc808729447, []int{7}
}

func (m *ResponseShutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseShutdown.Unmarshal(m, b)
}
func (m *ResponseShutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseShutdown.Marshal(b, m, deterministic)
}
func (m *ResponseShutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseShutdown.Merge(m, src)
}
func (m *ResponseShutdown) XXX_Size() int {
	return xxx_messageInfo_ResponseShutdown.Size(m)
}
func (m *ResponseShutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseShutdown.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseShutdown proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("rpcMsg.RPCType", RPCType_name, RPCType_value)
	proto.RegisterType((*RequestHello)(nil), "rpcMsg.RequestHello")
	proto.RegisterType((*ResponseWelcome)(nil), "rpcMsg.ResponseWelcome")
	proto.RegisterType((*RequestSetStation)(nil), "rpcMsg.RequestSetStation")
	proto.RegisterType((*ResponseAnnounce)(nil), "rpcMsg.ResponseAnnounce")
	proto.RegisterType((*RequestSendFile)(nil), "rpcMsg.RequestSendFile")
	proto.RegisterType((*ResponseSendFile)(nil), "rpcMsg.ResponseSendFile")
	proto.RegisterType((*RequestShutdown)(nil), "rpcMsg.RequestShutdown")
	proto.RegisterType((*ResponseShutdown)(nil), "rpcMsg.ResponseShutdown")
}

func init() { proto.RegisterFile("rpcMsg.proto", fileDescriptor_a4b9afc808729447) }

var fileDescriptor_a4b9afc808729447 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0xc7, 0x9b, 0x6d, 0x5f, 0xbb, 0xef, 0xb0, 0x0e, 0xd7, 0xdb, 0x58, 0xe9, 0x05, 0xaa, 0x72,
	0x81, 0x26, 0x2e, 0x36, 0x69, 0x3c, 0x41, 0x69, 0x3d, 0x52, 0x91, 0x3a, 0x25, 0x4e, 0xa9, 0xc4,
	0x4d, 0x55, 0x52, 0x2b, 0x54, 0xa4, 0x71, 0x88, 0x53, 0x10, 0xef, 0xc0, 0x63, 0x20, 0x9e, 0x87,
	0x47, 0x42, 0xb1, 0x93, 0xa6, 0xe9, 0xa6, 0x22, 0xc1, 0xe5, 0xf9, 0x9f, 0x93, 0xdf, 0xf9, 0xdb,
	0x3e, 0x27, 0x70, 0x92, 0xc4, 0xfe, 0x48, 0x06, 0xd7, 0x71, 0x22, 0x52, 0x81, 0xeb, 0x3a, 0x32,
	0xbf, 0x1b, 0x70, 0xe2, 0xf2, 0xcf, 0x6b, 0x2e, 0x53, 0x8b, 0x87, 0xa1, 0xc0, 0x6d, 0x68, 0xac,
	0x64, 0xe0, 0x7d, 0x8b, 0x79, 0xdb, 0xe8, 0x1a, 0x57, 0x4d, 0xb7, 0x08, 0xb3, 0xcc, 0x7a, 0x11,
	0x8f, 0x45, 0x92, 0xb6, 0x0f, 0xba, 0xc6, 0xd5, 0xff, 0x6e, 0x11, 0xe2, 0x2e, 0x3c, 0xf2, 0x45,
	0x94, 0x26, 0x22, 0xa4, 0xf3, 0x15, 0x6f, 0x1f, 0xaa, 0xec, 0xb6, 0x84, 0x9f, 0xc3, 0xa9, 0x4c,
	0x62, 0x9f, 0xf1, 0xe4, 0x0b, 0x4f, 0x14, 0xe2, 0x48, 0x15, 0xed, 0xa8, 0x26, 0x81, 0xc7, 0x2e,
	0x97, 0xb1, 0x88, 0x24, 0x9f, 0xf2, 0xd0, 0x17, 0x2b, 0xbe, 0xdf, 0x90, 0x14, 0x51, 0x40, 0xd7,
	0x2b, 0x65, 0xa8, 0xe9, 0x16, 0xa1, 0x29, 0xa0, 0x95, 0x1f, 0x8a, 0xf1, 0x94, 0xa5, 0xf3, 0x74,
	0x29, 0xa2, 0x3d, 0xa0, 0x67, 0x00, 0x52, 0x17, 0x95, 0xac, 0x2d, 0xe5, 0xcf, 0xe7, 0x33, 0x2d,
	0x40, 0x85, 0xef, 0x5e, 0x14, 0x89, 0x75, 0xe4, 0xef, 0x33, 0xde, 0x81, 0x63, 0xe5, 0x34, 0x83,
	0xe9, 0xab, 0xdc, 0xc4, 0xe6, 0xeb, 0xec, 0x06, 0x72, 0xeb, 0xd1, 0xe2, 0x6e, 0x19, 0xfe, 0x2d,
	0x08, 0x97, 0x96, 0x0a, 0x92, 0xf9, 0xa6, 0x84, 0x7f, 0x5c, 0xa7, 0x0b, 0xf1, 0xf5, 0x1f, 0x6e,
	0xa5, 0xd2, 0x20, 0xa7, 0xbd, 0xf8, 0x65, 0x40, 0xc3, 0x1d, 0xf7, 0xd5, 0xf7, 0x2d, 0x68, 0xba,
	0xe4, 0xed, 0x84, 0x30, 0x6f, 0x66, 0x11, 0xdb, 0x76, 0x50, 0x0d, 0x3f, 0x01, 0x5c, 0x48, 0x8c,
	0x78, 0xcc, 0xeb, 0x79, 0x43, 0x87, 0x22, 0x03, 0x9f, 0x03, 0x2a, 0x75, 0x3a, 0xb8, 0x1b, 0xda,
	0x04, 0x1d, 0x54, 0x54, 0x6b, 0xe2, 0x0d, 0x9c, 0x29, 0x45, 0x87, 0x5a, 0x65, 0x63, 0x87, 0x32,
	0x32, 0x9b, 0x12, 0xbb, 0xef, 0x8c, 0x08, 0x3a, 0xc2, 0x17, 0xd0, 0xda, 0xa8, 0x3d, 0x4a, 0x9d,
	0x09, 0xed, 0x13, 0xf4, 0xdf, 0xa6, 0x98, 0x51, 0x32, 0x1b, 0xd2, 0x77, 0x3d, 0x7b, 0x38, 0x40,
	0xf5, 0x0a, 0x82, 0x11, 0xaa, 0xda, 0x35, 0x2a, 0x88, 0x4d, 0xbf, 0xe3, 0xdb, 0x1f, 0x06, 0xb4,
	0xfa, 0xfa, 0xa9, 0x47, 0x32, 0xc8, 0x66, 0x75, 0xe9, 0x73, 0xdc, 0x83, 0x53, 0x6b, 0x1e, 0x2d,
	0x42, 0xae, 0xb6, 0x66, 0x24, 0x03, 0x7c, 0x7e, 0x9d, 0x2f, 0xd8, 0xf6, 0x3a, 0x75, 0x2e, 0x4b,
	0xb5, 0x32, 0xd6, 0x66, 0x0d, 0xdb, 0x70, 0xa6, 0x11, 0xe5, 0x8c, 0x66, 0x9c, 0xa7, 0x3b, 0x9c,
	0x32, 0xdb, 0x69, 0xef, 0xc2, 0x8a, 0x59, 0x33, 0x6b, 0xb7, 0x3f, 0x0d, 0x40, 0x7a, 0x91, 0xb6,
	0x5c, 0x5a, 0xd0, 0x2a, 0x5a, 0xe8, 0x09, 0xc8, 0x1a, 0x5c, 0xde, 0x6b, 0xa0, 0x73, 0xf7, 0xf1,
	0x9b, 0xb9, 0xa9, 0x6d, 0x91, 0xf2, 0xa7, 0x7e, 0x90, 0x94, 0xe7, 0x1e, 0x20, 0xe5, 0x19, 0xb3,
	0xf6, 0xea, 0xe2, 0xfd, 0x59, 0xfc, 0x29, 0xb8, 0x51, 0xbf, 0x21, 0x5f, 0x84, 0x37, 0xba, 0xf2,
	0x43, 0x5d, 0x09, 0x2f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xe7, 0xaa, 0x49, 0xa7, 0x04,
	0x00, 0x00,
}
